CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    CREATE TABLE "Departments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(250),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    CREATE TABLE "Employees" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(50) NOT NULL,
        "LastName" character varying(50) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "DocumentNumber" character varying(20) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "JobTitle" character varying(100) NOT NULL,
        "Salary" numeric(18,2) NOT NULL,
        "HireDate" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL,
        "ProfessionalProfile" character varying(500),
        "EducationLevel" integer NOT NULL,
        "DepartmentId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    INSERT INTO "Departments" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
    VALUES (1, TIMESTAMPTZ '2025-12-13T14:44:57.310067Z', 'Gestión de personal', 'Recursos Humanos', NULL);
    INSERT INTO "Departments" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
    VALUES (2, TIMESTAMPTZ '2025-12-13T14:44:57.310069Z', 'Sistemas y desarrollo', 'Tecnología', NULL);
    INSERT INTO "Departments" ("Id", "CreatedAt", "Description", "Name", "UpdatedAt")
    VALUES (3, TIMESTAMPTZ '2025-12-13T14:44:57.310069Z', 'Logística y mantenimiento', 'Operaciones', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Employees_DocumentNumber" ON "Employees" ("DocumentNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Employees_Email" ON "Employees" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Departments"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Departments") + 1,
            nextval(pg_get_serial_sequence('"Departments"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213144457_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251213144457_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    ALTER TABLE "Employees" ADD "ContractType" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    ALTER TABLE "Employees" ADD "DateOfBirth" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    ALTER TABLE "Employees" ADD "Shift" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    UPDATE "Departments" SET "CreatedAt" = TIMESTAMPTZ '2025-12-13T14:51:14.304531Z'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    UPDATE "Departments" SET "CreatedAt" = TIMESTAMPTZ '2025-12-13T14:51:14.304532Z'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    UPDATE "Departments" SET "CreatedAt" = TIMESTAMPTZ '2025-12-13T14:51:14.304532Z'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251213145114_AddExcelFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251213145114_AddExcelFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

